name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{b099463e-e2a3-45c1-beb0-2afd77c045a4}}
          heroku_app_name: "gentle-ridge-06046"
          heroku_email: "shobair.abidi@gmail.com"